"$schema" = "./node_modules/wrangler/config-schema.json"
name = "slapshot-academy"
compatibility_date = "2026-02-01"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"